// Seed Data for KPI Management System
// Generated by Database Engineer Agent

import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

// Ensure DATABASE_URL is set (use default SQLite path if not set)
if (!process.env.DATABASE_URL) {
  process.env.DATABASE_URL = 'file:./dev.db'
}

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Clean existing data
  await prisma.dashboardItem.deleteMany()
  await prisma.dashboard.deleteMany()
  await prisma.dataPoint.deleteMany()
  await prisma.kPI.deleteMany()
  await prisma.businessLine.deleteMany()

  // Create Business Lines
  const outsource = await prisma.businessLine.create({
    data: {
      name: '외주',
      description: '아웃소싱 서비스',
      color: '#3B82F6', // blue
    },
  })

  const b2b = await prisma.businessLine.create({
    data: {
      name: 'B2B',
      description: '컨설팅 기업 대상',
      color: '#10B981', // green
    },
  })

  const anyon = await prisma.businessLine.create({
    data: {
      name: 'ANYON',
      description: 'B2C 프로덕트',
      color: '#8B5CF6', // purple
    },
  })

  console.log('✅ Business Lines created')

  // Create KPIs for 외주
  const outsourceRevenue = await prisma.kPI.create({
    data: {
      name: '월 매출',
      description: '외주 월간 매출',
      unit: '만원',
      targetValue: 1000,
      currentValue: 750,
      measurementType: 'MONTHLY',
      category: '매출',
      businessLineId: outsource.id,
    },
  })

  const outsourceLeads = await prisma.kPI.create({
    data: {
      name: '신규 리드',
      description: '월간 신규 문의 수',
      unit: '명',
      targetValue: 50,
      currentValue: 38,
      measurementType: 'MONTHLY',
      category: '마케팅',
      businessLineId: outsource.id,
    },
  })

  const outsourceConversion = await prisma.kPI.create({
    data: {
      name: '전환율',
      description: '리드 → 거래 전환율',
      unit: '%',
      targetValue: 20,
      currentValue: 15.5,
      measurementType: 'MONTHLY',
      category: '영업',
      businessLineId: outsource.id,
    },
  })

  // Create KPIs for B2B
  const b2bRevenue = await prisma.kPI.create({
    data: {
      name: '월 매출',
      description: 'B2B 월간 매출',
      unit: '만원',
      targetValue: 1500,
      currentValue: 1200,
      measurementType: 'MONTHLY',
      category: '매출',
      businessLineId: b2b.id,
    },
  })

  const b2bActiveClients = await prisma.kPI.create({
    data: {
      name: '활성 고객사',
      description: '현재 계약 중인 고객사 수',
      unit: '개사',
      targetValue: 10,
      currentValue: 8,
      measurementType: 'REALTIME',
      category: '영업',
      businessLineId: b2b.id,
    },
  })

  // Create KPIs for ANYON
  const anyonMRR = await prisma.kPI.create({
    data: {
      name: 'MRR',
      description: 'Monthly Recurring Revenue',
      unit: '만원',
      targetValue: 500,
      currentValue: 320,
      measurementType: 'MONTHLY',
      category: '매출',
      businessLineId: anyon.id,
    },
  })

  const anyonActiveUsers = await prisma.kPI.create({
    data: {
      name: '활성 사용자',
      description: '월간 활성 사용자 수',
      unit: '명',
      targetValue: 1000,
      currentValue: 650,
      measurementType: 'MONTHLY',
      category: '사용자',
      businessLineId: anyon.id,
    },
  })

  const anyonChurnRate = await prisma.kPI.create({
    data: {
      name: '이탈률',
      description: '월간 구독 취소율',
      unit: '%',
      targetValue: 5,
      currentValue: 7.2,
      measurementType: 'MONTHLY',
      category: '사용자',
      businessLineId: anyon.id,
    },
  })

  console.log('✅ KPIs created')

  // Create sample data points (last 30 days)
  const today = new Date()
  for (let i = 30; i >= 0; i--) {
    const date = new Date(today)
    date.setDate(date.getDate() - i)

    // Outsource revenue data points
    await prisma.dataPoint.create({
      data: {
        value: 700 + Math.random() * 100, // 700-800
        timestamp: date,
        source: 'auto',
        kpiId: outsourceRevenue.id,
      },
    })

    // Outsource leads data points
    await prisma.dataPoint.create({
      data: {
        value: 30 + Math.floor(Math.random() * 20), // 30-50
        timestamp: date,
        source: 'auto',
        kpiId: outsourceLeads.id,
      },
    })

    // B2B revenue data points
    await prisma.dataPoint.create({
      data: {
        value: 1100 + Math.random() * 200, // 1100-1300
        timestamp: date,
        source: 'auto',
        kpiId: b2bRevenue.id,
      },
    })

    // ANYON MRR data points
    await prisma.dataPoint.create({
      data: {
        value: 280 + Math.random() * 80, // 280-360
        timestamp: date,
        source: 'auto',
        kpiId: anyonMRR.id,
      },
    })
  }

  console.log('✅ Data points created (30 days)')

  // Create default dashboard for each business line
  const outsourceDashboard = await prisma.dashboard.create({
    data: {
      name: '외주 대시보드',
      description: '외주 비즈니스 라인 통합 대시보드',
      isDefault: true,
      businessLineId: outsource.id,
      layout: JSON.stringify({
        cols: 12,
        rows: 6,
      }),
    },
  })

  const b2bDashboard = await prisma.dashboard.create({
    data: {
      name: 'B2B 대시보드',
      description: 'B2B 비즈니스 라인 통합 대시보드',
      isDefault: true,
      businessLineId: b2b.id,
      layout: JSON.stringify({
        cols: 12,
        rows: 6,
      }),
    },
  })

  const anyonDashboard = await prisma.dashboard.create({
    data: {
      name: 'ANYON 대시보드',
      description: 'ANYON B2C 프로덕트 대시보드',
      isDefault: true,
      businessLineId: anyon.id,
      layout: JSON.stringify({
        cols: 12,
        rows: 6,
      }),
    },
  })

  console.log('✅ Dashboards created')

  // Create dashboard items for 외주 dashboard
  await prisma.dashboardItem.create({
    data: {
      type: 'METRIC_CARD',
      title: '월 매출',
      dashboardId: outsourceDashboard.id,
      kpiId: outsourceRevenue.id,
      position: JSON.stringify({ x: 0, y: 0, w: 4, h: 2 }),
      config: JSON.stringify({ showTrend: true, showTarget: true }),
    },
  })

  await prisma.dashboardItem.create({
    data: {
      type: 'METRIC_CARD',
      title: '신규 리드',
      dashboardId: outsourceDashboard.id,
      kpiId: outsourceLeads.id,
      position: JSON.stringify({ x: 4, y: 0, w: 4, h: 2 }),
      config: JSON.stringify({ showTrend: true, showTarget: true }),
    },
  })

  await prisma.dashboardItem.create({
    data: {
      type: 'METRIC_CARD',
      title: '전환율',
      dashboardId: outsourceDashboard.id,
      kpiId: outsourceConversion.id,
      position: JSON.stringify({ x: 8, y: 0, w: 4, h: 2 }),
      config: JSON.stringify({ showTrend: true, showTarget: true }),
    },
  })

  await prisma.dashboardItem.create({
    data: {
      type: 'LINE_CHART',
      title: '매출 추이',
      dashboardId: outsourceDashboard.id,
      kpiId: outsourceRevenue.id,
      position: JSON.stringify({ x: 0, y: 2, w: 12, h: 4 }),
      config: JSON.stringify({ showTarget: true, period: 30 }),
    },
  })

  console.log('✅ Dashboard items created')

  console.log('🎉 Seeding completed!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
